SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE TABLE public.accounting_equipment (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    equip_type character varying(20) NOT NULL,
    model character varying(100) NOT NULL,
    modification character varying(100) NOT NULL,
    length_cm integer,
    quantity integer NOT NULL,
    cells character varying(100) NOT NULL,
    image character varying(500) NOT NULL,
    description text NOT NULL,
    cpu character varying(10) NOT NULL,
    CONSTRAINT accounting_equipment_length_cm_check CHECK ((length_cm >= 0)),
    CONSTRAINT accounting_equipment_quantity_check CHECK ((quantity >= 0))
);




ALTER TABLE public.accounting_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.accounting_repairrequest (
    id bigint NOT NULL,
    quantity_requested integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    confirmed_at timestamp with time zone,
    approved_user_id integer,
    equipment_id bigint NOT NULL,
    requesting_user_id integer,
    CONSTRAINT accounting_repairrequest_quantity_requested_check CHECK ((quantity_requested >= 0))
);





ALTER TABLE public.accounting_repairrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_repairrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);





ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);





ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);





ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);





CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);





ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);





ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);





ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);





ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);





ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);





COPY public.accounting_equipment (id, name, equip_type, model, modification, length_cm, quantity, cells, image, description, cpu) FROM stdin;
5	Материнская плата 20*22,5 (см)	android_board	DZ-982PVHL-G00S-V1.1	8+128	\N	5	2	https://sun9-77.userapi.com/s/v1/ig2/2fAm8P5erxcehZ3OP4PAK-9XE09qPK2bRIRRMoUlHgfR4R5xJe1S2ZcL8i27-LmqA-Tby5bfyDGlQoAv5IT9Ft5o.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&cs=1920x0	Панели 55" / 65" / 75" / 86"\r\nDP -\r\nType C -	
4	Материнская плата 20*22,5 (см)	android_board	DZ-982PVEJ-G00S-V1.13	4+32	\N	3	1	https://sun9-24.userapi.com/s/v1/ig2/tFK99VtdSYshkxU7BJgBPnFfZ_edhNn6LSMQjaD8QRzSU3YshT23VAE8uvwd4VfELg_lQ2dJpDgAE0eUqPFTvh2h.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=YJA92rapAmnTGFFoxzJnwQiANL7ekY8P-5UVYmEI3U8&cs=1920x0	Панели 55" / 65" 75" / 86"\r\nDP -\r\nType C -	
10	Плата питания 29*21 (см)	android_board	MP380SL-5R34	8+128	\N	7	4	https://sun9-78.userapi.com/s/v1/ig2/ANPDxA2nfA2787CIzWZaohTx41UjpRnmiqJmaecZgZmB_6tDaFWkhuz7Ssp0KiroV6Ql1pZVqaX5IrOTzGRDeCle.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=vzK-KcKFg2l01FcmJsuaCaVBlvNPV7bvqpcbH8_badc&cs=1920x0	Плата питания для панелей 75"	
8	Плата питания 32*23 (см)	android_board	MP360SL-L4-S20	4+32	\N	6	3	https://sun9-72.userapi.com/s/v1/ig2/RZ6eeEt2QXECSu95Fm0HRcvTZfvg3u20E6VnraT3APGjsFFCLa61XSNCkfi9B4IX5vM6PjF13BwkoEnnff_MtzA8.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x479,480x639,540x719,640x852,720x959,1080x1438,1280x1705,1440x1918,1922x2560&from=bu&u=ms6r6iXmTW7ueB_zVCibDOguJNfzhF6t8lWvFu-FKn4&cs=1922x0	Панели 65" / 75"	
9	Плата питания 32*23 (см)	android_board	MP380SL-5R62		\N	3	3	https://sun9-83.userapi.com/s/v1/ig2/0uG9DyhaU5KccJDCGdPWrZDqox-ndN57VpD97ORtkt-UL4CfxDdg-qPC6VbfxuZHMBzS6OQLKbiK3JCB86sYT_CR.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&cs=1920x0		
16	Материнская плата для панели	windows_board	ELSKY QM8000 - 2C		\N	1	5	https://sun9-64.userapi.com/s/v1/ig2/9xEx0iGXGuaY387-w4F3fksF6TSQ01QaFO8f-dbPr0EW1wFxj-N_idwGqu_-PUNKN75IZOjXssmackP3AYzeAAkD.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=1uv_ksZeciDsPQio5K2mD8n4BMjgRaaGznCX6UAtxnU&cs=1920x0	панели 32" /43" / 49"	Неизвестно
6	Материнская плата 20*22,5 (см)	android_board	DZ-B-982P-V1.3	4+32	\N	1	2	https://sun9-79.userapi.com/s/v1/ig2/8DilTBrB9-jquWUu534PFu2hAi3lPfsyHXNTZ5C7Wm1iJBaY1ljH_HxK84snhmDY9RaNhGmQB5_nk-YQxWra940C.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&cs=2560x0	Для старых панелей 65"	
2	Материнская плата 28*24 (см)	android_board	DZ-982PVHL-GD0ALNOVW-V2.0	8+128	\N	6	1	https://sun9-48.userapi.com/s/v1/ig2/1q3QCzEemzRI8x2PLFtMdMyG6GOm9nbND_MwonQoY9Dc3TNBQ8ZQhDCSZaG2OQBWqlVN82dlX-UWf-r3hUPX9dKA.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&cs=1920x0	Панель 65" / 75" / 86"\r\nDP +\r\nType C +	
1	Материнская плата 28*24 (см)	android_board	DZ-982PVEJ-GD0ALNOVW-V2.13	4+32	\N	5	1	https://sun9-45.userapi.com/s/v1/ig2/aPwHNVxeuOJnP92xBhnqdP68aAX_bQPnoDn66SzPeXdKD-i2DqYeU2dJZ-AWxMfSfMdPwe0QkS044LltIbapJ24D.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x479,480x639,540x719,640x852,720x959,1080x1438,1280x1705,1440x1918,1922x2560&from=bu&cs=1922x0	Панели 65" / 75" / 86"\r\nББ 75" / 86"\r\nDP +\r\nType C +	
7	Материнская плата 28*24 (см)	android_board	DZ-982PVEJ-GD0ALVW-V2.0	4+32	\N	2	2	https://sun9-62.userapi.com/s/v1/ig2/6irlv3E2HqGAV5lrqjeuWLSWkP2vhEoOrdOnwUOQEneUQjotKyjAok9JrF45kTD89evA-xgZwQZ5exbW6GY33z7Z.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&cs=1920x0	Панели 65" / 75" / 86"\r\nDP +\r\nType C +	
11	Плата питания 29*20 (см)	android_board	MP330SL-5R34X-D16	8+128	\N	2	4	https://sun9-52.userapi.com/s/v1/ig2/RgCDnK5TW9O_Zory9IGVGYbHkEOjQEm4r_QKexQM-qCrm9cPpfL4PShHKUicnye4dpTDGHJAvDxwW5PwxV0GVkCI.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=Qj-WbyMTn_vzW6xEGTnH1MP3GwEcTH9sTIOpaeK9bX8&cs=1920x0		
12	Плата питания 32*23 (см)	android_board	MP550SM-5S34-AD	Неизвестно	\N	2	4	https://sun9-23.userapi.com/s/v1/ig2/2KoQWHd03xR69k7VRpYfWLLL6eVTBJ1fIFITIYR_EDmGNNW8YcqSkbZuZmtwSE17tevzl31OKlmSjngF--FLE9el.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=QI5yKXvF1DHzXhTEjIA4a3QVjcPxfqh7eG9R-ErTKJA&cs=1920x0		
13	Материнская плата для панели	windows_board	QM6616- I5-3320M		\N	3	5	https://sun9-76.userapi.com/s/v1/ig2/brBNzQwd14cbHBLnOyriRGBoCAFz8EcBl_dKkDYwKdm8lWFBW7tBwIMwEIN7PM8oxaC0QRDXIHr1wALix0UUEs3O.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=kM15Kny_Ry9yUam_kv9KUmiWba0mwW36_-nMhs3Jayg&cs=1920x0		I5-3320M
15	Материнская плата для панели	windows_board	QM8000 - i3 - 4170		\N	1	5	https://sun9-72.userapi.com/s/v1/ig2/udn2jCN8AnvvBaEB8pWiKCgX2HuN3JqhRvBOIb0lwlNA_vzBz6cq4do3pzhgUBIc6q7KNVj_pw_uwZMVKabqcnCi.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=QSSwQI2GVKl2FPIi9hd50O86KO30RVIcSaO4rAQBRXo&cs=1920x0	Панель 32 " / 43" / 49"	i3 - 4170
14	Материнская плата для панели	windows_board	QM6616 - I3-3120M		\N	1	5	https://sun9-54.userapi.com/s/v1/ig2/JyNHFFxdrBHi2DuZErGNK_pYp-FLNXhzIdbmNDZfL96v5aP0GthRSZRwlcFkJat5o6hxFZr-qjkFLfsVlv6N5DCB.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=JgQ5wU-nJwnOLgT7HsplP9hEZcVzsZ9hUvzlP4Pv0vw&cs=1920x0	Панели 32" / 43" / 49"	I3-3120M
22	Плата питания 28*19 (см)	android_board	ZW9300-A-01-P02		\N	1	6	https://sun9-11.vkuserphoto.ru/s/v1/ig2/sqJYdzVoW4SFfFljNM_5tK6Uis-Av3cfShw1ddBYYtlnpXP4OJzhrB8tgHoWkahr4HATPfM5oCVTeYEPt0sy5bLc.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=Bht73k1HP-Em-mwfQ3QCw-5K0DGQYf0E29jTYd4BH3w&cs=1920x0	Плата питания андроид 6 (снята с ИП Рудюк)	
21	Плата питания 28*19 (см)	android_board	TOSN-LD5518P		\N	10	6	https://sun9-41.vkuserphoto.ru/s/v1/ig2/SinINnR2enSwV0PEQWCbWPQsZzsJIaIp5bxiBFKQyHq9Jya08qGM271_vmHhyDfvW1AULZYi6LUOfr2ife8Qr_Vl.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=kzu4wi71vsTPslS6PWgPdmR--5u0DxXaXiteyrIixtU&cs=1920x0	Платы питания для старых панелей 55"	
20	Плата питания 28*19 (см)	android_board	TOSN-LD6518P		\N	1	6	https://sun9-1.vkuserphoto.ru/s/v1/ig2/RXubWF2mFuj_RLKgIgTcOlHi97eYkJorlwPehCjB15jDSSjr3eHYuIwoLfHHQ5TDvYXS6azrBUFZSyTOWE1nnJpp.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&cs=1920x0		
3	Материнская плата 20*22,5 (см)	android_board	DZ-982PVEJ-G00S-V1.1	4+32	\N	2	1	https://sun9-35.userapi.com/s/v1/ig2/z9CZkcF9lobmSdHKplUQdY0u0CE89VMpkerStS6CPxGm8DNbhlPQnq6mlgVFi7ivV9Ufsyf6NtNwhzJvH3vhnUyC.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=4u9ACG7-iAXq550gr33s_RcGJ022wQ06Hv97TLTsubc&cs=1920x0	Панели 55" / 65" / 75" / 86"\r\nDP -\r\nType C -	
23	Плата питания 18*11 (см)	windows_board	JP3250PL		\N	2	6	https://sun9-82.vkuserphoto.ru/s/v1/ig2/5K6NQBpVUAsEgSslU0xdfl7xWQTFD4PiKb3jeyxfqjr624SJW9pg1gSTJdUA-1R61i69D8LRrLEzs7i9RUcDElel.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=OK1jD3X2wTOA3vXYzH1R97BsiTVVVCXnSprA99JJD7c&cs=1920x0	Панели 32"	
24	Плата питания 18*11 (см)	windows_board	JP3250AL		\N	2	6	https://sun9-57.vkuserphoto.ru/s/v1/ig2/7og23eIO7-ZwL96WZTqxhtrCkwrDSJV2u67hWIQ1CSn_P3r3JiPFMzWcX2VzAM2RZ7wf-oW8fL2GTda9U3Z1dO-v.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=cdhckE6uPNluP5ltC9sQItXA4CVZEuJTnKHuLCAyW_U&cs=1920x0	Панели 43" / 49"	
19	Материнская плата для OPS	windows_board	I3-4160		\N	3	5	https://sun9-15.vkuserphoto.ru/s/v1/ig2/56duz9R1YcuRr0cDvkRDUet5BDuCI6CpSTzZQdU-m-abVr8e3d1N5m3pM_7HF3zomih_MwDXYgNi5-JL2XWEFpp7.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=u1fuY7yTZvzkOeqk0n2VXkSVrmc1svnN0He05pZr1PU&cs=1920x0	USB Type C -	I3-4160
18	Материнская плата для OPS	windows_board	I5-11400		\N	4	5	https://sun9-34.vkuserphoto.ru/s/v1/ig2/1zzX0GBXpsfE5zPPJKYFzYG61RL3ZUaBiDUnGlkOlfBtn2bmc4GKJHRozBLS4-ffnaPYprEdXYX7-SI9VRPnAzni.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=RQQQMvPTT3Y38yV1ktomzMV08MhegA41hDqE8xLwjKk&cs=1920x0	USB Type C -	I5-11400
17	Материнская плата для панели	windows_board	BNY-I3-3120M-X86		\N	3	5	https://sun9-18.userapi.com/s/v1/ig2/27kK0snGjio6Z3aXgUAlVzTKe--mnHaKQ6V6BoDYjo9i_DDZmnDBLQ3I7yQyovRYruc9AQ0WNlRvtK_TQkeWB5TQ.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=TZLntMPdoWJGk4csjARFWcUj21cV8DA1JCwX2IW9fWI&cs=1920x0	Панели 32" / 43"/ 49"	I3-3120M
30	Плата питания Видеостены	videowall	PW.186W1.801		\N	2	7	https://sun9-27.userapi.com/s/v1/ig2/LcL2241CkLaehKKSuo3uxnVimYj6mp-Aj3tuI5kWx-TfoxPtI4962bGuYk52HB6kyRPR9y-cDX0-dsqo_uVLGnfh.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=QZ7qBqV-qRekLiX_s3vCn03hbz0nFMDCnKJQYlnruZo&cs=1920x0		-
28	Плата питания Видеостены	videowall	JP150L		\N	2	7	https://sun9-29.userapi.com/s/v1/ig2/XewOkoHMbBUQUHR0aqwrBEqZQZr_ZOhGMpuhClMxlAleJyEZYn18hOGGEJa95j_CDbCBPV-vq1AB5UvlexEUWliL.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=-sdilpmMkQbka9hA0vwJM75y-pyUHFZRnjMf96jNyVE&cs=1920x0		-
27	Плата питания Видеостены	videowall	ZW8160		\N	2	7	https://sun9-84.userapi.com/s/v1/ig2/tWQYkr64GalQTQi7DXlM_1g02VdQyfjv5dkMJdJf_o2tmoib5wegoSolyBr7i9Bt5XkMxUlsnC7H8_qgFKsUIwYH.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=yKpneU4xAlnk5jAeRl1uBttcYt8tYc33i8-6svhaaFQ&cs=1920x0	Плата для видеостены	-
29	Плата питания Видеостены	videowall	TOSN-LD4209P		\N	2	7	https://sun9-2.userapi.com/s/v1/ig2/FckhDfaz_lzsbZbWe8nvPMWDEKjbVl65PzWVDYBAsBK3BjlVmo__m2JJNZlsFUXO0w8OExFJ6O-SwbhzesWYKw8j.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=b-vxBXaWqf3__QAQZnGSH_JrWulzkorCDIUiQYzF0Yw&cs=1920x0		-
26	Плата драйвера ЖК-экрана	videowall	M56W-V2.0		\N	2	7	https://sun9-52.userapi.com/s/v1/ig2/-T_jk2-DVSQgnAWyIbhIYPwqApIDdfn4ED3tSLUACezMglJL5d12gyOLKWZFh_D7jRi_XhtGrd4KM7pFe50r0OiA.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=zHiz3v6rz5Y90Z1CLVskIvhwBZ9CAbka8rlt3BpqJ58&cs=1920x0	Плата видеостены	
25	Плата питания для панели	windows_board	JP4265AL		\N	1	6	https://sun9-51.userapi.com/s/v1/ig2/1quWazADO42vAJzICV3XVCqRJpyZivlXwMQWCWcx-PF_EEwop9Kjmc-OcFlD4AqPZZ2PnAKqTexDkOFPZsC10hZD.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x479,480x639,540x719,640x852,720x959,1080x1438,1280x1705,1440x1918,1922x2560&from=bu&u=oQRcaaMkwI8UrlqOfi2Szr_SCaZI_LvH8kEKRiWXavg&cs=1922x0	Панель 32"	
32	Плата питания 18*8,5 (см)	android_board	TOSN-LD1215P	4+32	\N	1	6	https://sun9-61.userapi.com/s/v1/ig2/NRybiYEWx2iSBdG7dS8HxQ50j2lUEAyXTmtGSFJ4_oQvpL9NTNYv8FUhY15wmFf9m3UxX8wsLRaawwIpSAi4DWa-.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=AGhGC19FMlgyhsbgaMXwN7fcgOljgMx2YX-RI7-KC1I&cs=1920x0	Плата для Панели 65" на андроиде 6 (ИП рудюк)	
33	Плата питания Видеостены	videowall	MLT188T		\N	1	7	https://sun9-82.userapi.com/s/v1/ig2/B0ZqkBb0_BxtkoNXM6dNV8jzG_Q101DCWEZx-mDm0gKXeM8ovu-9Dv1A0sPBD0TE8UJ4oz2zOHSyOVWkgcIMH7Z_.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=oIhK1Yt9TA5JAs-eEWuRj7BlxhDvpU44z-_W_7q5H6k&cs=1920x0		
37	Шлейф 14 Pin (7)	cable	AWM 20624		7	100	8	https://sun9-82.vkuserphoto.ru/s/v1/ig2/ZfRkaRhxWBvfW0bTXjKfK3YMb3_X1_xkDG7e813znbIuJTPpncLMjUDtvDqIqrB7TiJ8tk-pmsJzYSaeQ49asyib.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x479,480x639,540x719,640x852,720x959,1080x1438,1280x1705,1440x1918,1922x2560&from=bu&u=58B9kqA0hl365XBxs3N6PfrYx9gISdApVH0B-5vzPos&cs=1922x0		
34	Шлейф 14 Pin (12)	cable	AWM 20624		12	62	8	https://sun9-72.vkuserphoto.ru/s/v1/ig2/LL95dGkZDepTD_GnOAwMsKBtnlzir0edti94cNHNPkyMvBcmZpAVylRGg6R6Rpitfy58DqVYGTfomK4qJA3Ag-ec.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=EP1rTgSoJj9BLBUmW9lA6J8vbnhleXodGJab8No_mf0&cs=2560x0		
35	Шлейф 14 Pin (20)	cable	AWM 20624		20	99	8	https://sun9-3.vkuserphoto.ru/s/v1/ig2/m-CQ7JheKUjPs082lz0MV1xVyVK1oxYGEbxWpc3fBJj_QwTFkXv6WDiyEYTrpcjYwoHBHfnrjd-fH3gL0q-xHZbx.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=1bgkwxM7uhZO-Zh95kDPBdy5s-pjeoiioWscxgkPVtg&cs=2560x0		
36	Шлейф 14 Pin (5)	cable	AWM 20624		5	90	8	https://sun9-83.vkuserphoto.ru/s/v1/ig2/aBRyW9Qo_Jpj8f94fbT0AZmJRFnmCREN7IgZClaKsR7xsXUSRuapi_6NIaqJjhk-Gbe2YH4xfJy89JYAc27eH2_T.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=r8YvNpzpnj78ZlHu2YHhRzOoBMgGUI2Dk0JYvYQRZaQ&cs=1920x0		
38	Шлейф 60 Pin (20)	cable	AWM 20706		20	20	8	https://sun9-2.userapi.com/s/v1/ig2/LZQmGVvmO3RerBEna3teRmuaBgYgOtbKZI0yWNKdvu7Tum3XQyO6wNRMD4bTG4zeUcQzuk1oq6M-IjAMd5jP55y3.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&cs=2560x0		
43	Шлейф 50 pin  (75)	cable	AWM 20890		75	13	8	https://sun9-46.vkuserphoto.ru/s/v1/ig2/w_DUf2M_aJMRuwbe06G-Ttxi3oyD1CF4luTDHyh-oV6VHbhsMpTtdc4ueQa9UlSyeaDyFh6TU1LmCZfDQpuVv7XH.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=uqv5N6paeK4b0hauiq_DQTF1LwkYdi1WwYB9cPi65jg&cs=2560x0		
31	Плата драйвера ЖК-экрана	videowall	M59W V2.3		\N	2	7	https://sun9-73.vkuserphoto.ru/s/v1/ig2/HmM8ywP6PXpyXYepXL0Ca-9OmBuIdF3PPU0UNIDIa3dfH38qHec6AaD_18kInLBe9OigMzL4S_DPI9bEowvA4pj9.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=ki4Uy9b6Lk-eeSrdZSriNGbesmIGd24kNHq80RWyHQg&cs=1920x0		
42	Шлейф 50 pin (90)	cable	AWM 20890		90	3	8	https://sun9-46.vkuserphoto.ru/s/v1/ig2/w_DUf2M_aJMRuwbe06G-Ttxi3oyD1CF4luTDHyh-oV6VHbhsMpTtdc4ueQa9UlSyeaDyFh6TU1LmCZfDQpuVv7XH.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=uqv5N6paeK4b0hauiq_DQTF1LwkYdi1WwYB9cPi65jg&cs=2560x0		
40	Шлейф 60 Pin (15)	cable	AWM 20706		15	4	8	https://sun9-14.userapi.com/s/v1/ig2/nXCof1XHsC0IMvvtoENhwVJ7EI_YgXFrGfd6z_7Ica0yUcpE7LG5vBBsYpS0msunOuI7CbvUrspkgIdDcZdjFu7R.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=TrrdSeiGYe-FXMja7SgvcguWE92JBXodsFV3OKCXstE&cs=1920x0		
41	Шлейф 90 Pin (15)	cable	AWM 20706		15	0	8	https://sun9-21.userapi.com/s/v1/ig2/lJMEe-aPa462X81a1HqPPkY6az-Lp1zFzFVetIhNaLwpmW8-c2yomeM6RyLRQEabONZAqt-CFuR-GbewbgQfYlse.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=Wex0XXev1N90rOl2dVPBljNu1tCF4QuNEnOiylwNo54&cs=1920x0		
44	Шлейф 50 pin (75)	cable	AWM 20890		75	2	8	https://sun9-26.vkuserphoto.ru/s/v1/ig2/56XjIRPnauhvzpdt-ytxdtF10U5dG2IULOO6xCGidmrrikT1iOJ1Hsgznq-iTERfEdIcF2IGjhY4NtnQFSPjsGzo.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=xySfvpAgsueEqNozUkzBtl40hgkM63kQl6X3ciStfM0&cs=1920x0		
39	Шлейф 60 Pin (10)	cable	AWM 20706		10	8	8	https://sun9-7.userapi.com/s/v1/ig2/ouZVcXrtbZq8saYLpYIpTAiSnjx__4vM_8HUxROGoXvZGcoasUUwuPeNp8xUI0yZxZDtL5LkBEvCDVKN8Mr8YaOk.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x479,480x639,540x719,640x852,720x959,1080x1438,1280x1705,1440x1918,1922x2560&from=bu&u=uvLPZy0z9QlA_6hRRofA7FoeBE2-v58ShQlkhS0jX9k&cs=1922x0		
47	Плата T-con SG7461D03-1	tcon	SG7461D03-1		\N	3	9	https://sun9-14.vkuserphoto.ru/s/v1/ig2/YWFagd6Mxlp30guZbH7hnFnIN9NUkm6BP2DWFycI_S-jveBQvkMVvpQ7qKrpiwPpYKvDraewTTTLiBboQG9RbGKM.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=yRIKLYpjm7LcQZyf1lGffT1K7JFHX4usSTF1sLRuB-g&cs=2560x0		
46	Шлейф 50 pin	cable	AWM 20706		75	7	8	https://sun9-19.vkuserphoto.ru/s/v1/ig2/ZKCmxPFPE3sJ-fLzHzdEQKAEONDXZx47IdCNNkHj8tpf2Lxtlf0uLoxy-J2Qvv2Q4uWJVt8KBSty6IJvARMrisC6.jpg?quality=95&as=32x38,48x57,72x86,108x129,160x191,240x287,360x430,480x573,540x645,640x764,720x860,1080x1290,1280x1528,1440x1719,2144x2560&from=bu&u=mHBdvRmw7kk3C9T7jg4stqr99YgewligZQltWoi-fYM&cs=2144x0		
45	Шлейф 50 pin	cable	AWM 20706		75	2	8	https://sun9-49.vkuserphoto.ru/s/v1/ig2/AXzJnvRjLMV5Bu_NutofFrMPwx01e_Ix30i35x9mrzkqr24HHHdxso0kNajNYiei9lMd_agW2NKhQdoWJtaK1-w3.jpg?quality=95&as=32x43,48x64,72x96,108x144,160x213,240x320,360x480,480x640,540x720,640x853,720x960,1080x1440,1280x1707,1440x1920,1920x2560&from=bu&u=DA_XtLw4ZN0ZSz0jsgRZlbGIzztSDkNkpbqLcaWaTNQ&cs=1920x0		
49	T-con TC.B550UHDQUB-F70.1	tcon	TC.B550UHDQUB-F70.1		\N	3	9	https://sun9-10.vkuserphoto.ru/s/v1/ig2/OS6zQss8B4Aryizz-e1Lg7gK8LfaDAy6Is9wy60u3lD2Elu6QQfb5ozwnYux5g_4MnOWXpoRTuYZfLWZF4EyPJR6.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=wOgMAjWXT6W4_3g8O9RpCvVTyyr0ozK8_U7PauJghec&cs=2560x0		
48	T-con ST4251B05-2-C-1	tcon	ST4251B05-2-C-1		\N	3	9	https://sun9-88.vkuserphoto.ru/s/v1/ig2/tClH_9ZmKE6oW8RlfuDucP91bFhJt-Eum1wbfvidJvxWdLfXc3-DFaiDeqfeoPS_J9QvGhBqptHDXFDwlPa9tm0k.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=kjaXsFc-j9vD1H0X5tqbscnfsvYQn0Xmq5L3p5Jrzpo&cs=2560x0		
50	T-con 65T55-C04 CTRL BD	tcon	65T55-C04 CTRL BD		\N	4	9	https://sun9-52.vkuserphoto.ru/s/v1/ig2/woYtb1v7CLQ1IpRsVAxfDOETaWp_ZToDHjIVdTMsE_4T_C6nYLoDxI2rUGF_xP71Pp5rTa0W3K3OZmx6ToRlnZ8e.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=d5tjEQSzmSofIFewGICIa4MPUqRkBS1_GksvsKC61EI&cs=2560x0		
52	T-con 55NB / 55OTW	tcon	55NB / 55OTW		\N	2	9	https://sun9-50.vkuserphoto.ru/s/v1/ig2/Y6OTe3UpYhWxH2Hn7UHdHsLPa662q0Oslo-KZbVfGJyv3uCRotVYrdljtdDmOuAYX5pVWVEnZIJ0cJ-DNg77lupC.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=asw9tVuN5-xnVvhA7iFqTiDmlTwVIxaWswLaFurbfuQ&cs=2560x0		
53	T-con 65 6871L	tcon	65 6871L		\N	2	9	https://sun9-39.vkuserphoto.ru/s/v1/ig2/O9Q5KOe3pakY7TZc5o189FxdmWA6e2mFqdZLJXb-7TZfUHsN1mygeQneyD2vqB4CY1sZnUAYgPzAiWMSlyQ0OrCf.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=2-o_isSq2tBMWj6cRtKe0lTKUtzfUlXg0o3rWJYNfqQ&cs=2560x0		
56	T-con 32T42-C0K	tcon	32T42-C0K		\N	2	9	https://sun9-47.vkuserphoto.ru/s/v1/ig2/MKB12BBJJ2_u8yx4pL8_qtk0mDHbyHI4C4u9SQFnpYY78IdLcYF_3xR8duaR8UacBbI4IJs2ld88LeHUWMPZtafA.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=BokxbyZ9UDVAR33fHHZ3_IlWl0wwOhbAnO_BxoXI66U&cs=2560x0		
54	T-Con HV320FHB-N02	tcon	HV320FHB-N02		\N	6	9	https://sun9-49.vkuserphoto.ru/s/v1/ig2/sTExY4X0tb12mINLvkHSxfCnbfv9QAsPAJr5WvBs5sQeKDnJbggu-4JEngYaadMd9gMztMGLO2WqNexiQlfEC32U.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=oRRvAHqzRKBIv6FbFuASjps8h-9J7zyAauVdwg3tkPQ&cs=2560x0		
57	T-con 85T14 C03 CTRL	tcon	85T14 C03 CTRL		\N	2	9	https://sun9-75.vkuserphoto.ru/s/v1/ig2/TwW4tiPNKw3GB_xO9bv1aAnaL_h6wAAol79cyGnQ0Lhpg3ByBOMzJscVfmJQZwPAHUzqofM5V88iE3tmDf9mRQvr.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=kRyWRGGaPAV5oH6XgYP2-zj7vs0gnBARKMqakNAB0Sc&cs=2560x0		
51	T-con LQ-K8-K03-12	tcon	LQ-K8-K03-12		\N	4	9	https://sun9-17.vkuserphoto.ru/s/v1/ig2/pM3rthYJWol_nE6o0Fh1joj__n4Wq_Av8dFiSNp4AU9KHoCt7VXwWA1_o2rjrN28Ak7DSXdMORLMcSKUt1ukmBp7.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=QU9nU5A7yvlqAYWLZYxpl2uTZwxCGM6CNfAtoOXLP8s&cs=2560x0		
58	T-con DCBDP-C260A_20	tcon	DCBDP-C260A_20		\N	2	9	https://sun9-88.vkuserphoto.ru/s/v1/ig2/kmMk49Pf2KRqouflAjMx2z2CSf77kRNoX6NHjcvd-tVdF9-m-6rau8BaMX05G9pEvgS8htBqiqyqgLWN0RtSe5Jc.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=bwj0hdXEZH81R0KhoHJ-U2R7poKic_IS1Ff5TvRhwQ0&cs=2560x0		
59	T-con 55A- UNB - PLUS-CPCB H/F	tcon	55A- UNB - PLUS-CPCB H/F		\N	1	9	https://sun9-85.vkuserphoto.ru/s/v1/ig2/BKBizHg7ci-coTB8a0N8JMHDXJeiPullpnv0EW5rhLcjoJ5WH4JCfd7Un_wFI_JnWJfJ97etegFpaG0mNFbTRcON.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=AqxyhBBUssN3f69lXR-wRVIkvb__P3KZ4oB8AIhOL0I&cs=2560x0		
60	T-con DCBU-C196A_13_P3	tcon	DCBU-C196A_13_P3		1	1	9	https://sun9-53.vkuserphoto.ru/s/v1/ig2/tvI8a_CzzRrUtbhiTOw5DqeZzgDSb7tERKnqmm3YTcwV6Zo-SCdAXHb14SpsYPS888lnotBPjKJf3TtEfgptjaby.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=NS9zYMd7Mt53zBh2j3-leKDImkWND8KgHOt4eKDDcok&cs=2560x0		
55	T-Con ST5461D07-1-C-D	tcon	ST5461D07-1-C-D		\N	2	9	https://sun9-74.vkuserphoto.ru/s/v1/ig2/iLmJv2Bo3D1cHtRldmkL1EisyVMIhQznzZ3Jeg3Q3-WbYx0cwsv5m8njI8EBmaRaaBWMcXqdm2v5xgJe-gRyl0_V.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=AocOIlitEUKS4lBahZi-KvEOlp_-REp2XgAG-f_PGAE&cs=2560x0	У 1 т-кона в комплекте 2 шлейфа\r\nУ другого в комплекте нет шлейфов	
61	T-con ST4251B05-2-C-1	tcon	ST4251B05-2-C-1		\N	1	9	https://sun9-18.vkuserphoto.ru/s/v1/ig2/SD123jss_LSXRZDXkmigV3n6vlaA7vb7zbAQn5T2Zj7HYcJyrYufZc7gNoWjLuqjnEkuNOgVSfJyj8dFenvdYAkr.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=ILzGD8BPAMvE8uiKEnCUy4ufG5s57amB-JxK9xQOMIw&cs=2560x0		
62	T-con HV490FHB-N80	tcon	HV490FHB-N80		\N	1	9	https://sun9-86.vkuserphoto.ru/s/v1/ig2/YR5ShBmvnhwhiEhkzSo4myyErDtFBgoG2HCC8aCIYbAqLXnOSZV8y5NO092jncojaCCiDxP4XuOOvt4GpX4HPjMG.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=Br73UBCN2VJ8vp1cqYagk_DVpp2AOSe-QcwfHrogaC8&cs=2560x0		
63	T-con ST7461D01-8	tcon	ST7461D01-8		\N	1	9	https://sun9-52.vkuserphoto.ru/s/v1/ig2/WFUqb0cT2dyHWv7UZTg7RPoNmA813TjpoV4-Buq_D2kt7LvJj8iAmOIhqn-y3ZXJwsdARG82S-ZYV5muAqRfKukw.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=xbRdKHSGlTotKpo5d1ArOpa17qcYBemurAvayEgCHbk&cs=2560x0		
64	T-con ST6451D02-E	tcon	ST6451D02-E		\N	1	9	https://sun9-27.vkuserphoto.ru/s/v1/ig2/eeHfZnQtjUgEhe9TPdoC6WguMc1Oi0aRv0yVKx8Xso8oLjaTsCN9Vaqt-DfQxthF0lbx5gslkSxTcswKoHTi55Nk.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x540,1080x810,1280x960,1440x1080,2560x1920&from=bu&u=9qopi60cgWuIcXusPoTXVtfJSAhP5xmmzLXmMDdkgV8&cs=2560x0		
65	Тач контроллер для 75" BlackBoard	tcon	Не известно		\N	6	10	https://sun9-6.vkuserphoto.ru/s/v1/ig2/da7mhlTk4paqQ7tF4IlnJJO-LEmsr6y_wJCHdy3WAniENjMvLieTjcJ7T2AhyvLOfSZl5qs-XWrxFcUPb3nx7t59.jpg?quality=95&as=32x24,48x36,72x54,108x81,160x120,240x180,360x270,480x360,540x405,640x480,720x541,1080x811,1280x961,1440x1081,2560x1922&from=bu&u=_1MA4JF0i0SgVtlUv9uY9kGMxFATmm3qKOdTKXoLYDQ&cs=2560x0		
\.


--
-- Data for Name: accounting_repairrequest; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.accounting_repairrequest (id, quantity_requested, status, created_at, confirmed_at, approved_user_id, equipment_id, requesting_user_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Единица оборудования	7	add_equipment
26	Can change Единица оборудования	7	change_equipment
27	Can delete Единица оборудования	7	delete_equipment
28	Can view Единица оборудования	7	view_equipment
29	Can add repair request	8	add_repairrequest
30	Can change repair request	8	change_repairrequest
31	Can delete repair request	8	delete_repairrequest
32	Can view repair request	8	view_repairrequest
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$JIRscctND5EoViTTMPVbKU$6Na4ymwjemTMyQ5AIEEDZR/n5Z2FSUO3UMew65Hk8JI=	2026-04-21 12:48:21.05661+00	t	admin				t	t	2026-04-07 02:34:37.245942+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-09 05:27:19.84883+00	1	Плата Android: Материнская плата 28*24(см) (DZ-982PVHL-GD0ALNOVW-V2.13)	1	[{"added": {}}]	7	1
2	2026-04-09 05:29:04.482037+00	1	Плата Android: Материнская плата 28*24 (см) (DZ-982PVHL-GD0ALNOVW-V2.13)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
3	2026-04-09 05:31:47.111329+00	2	Плата Android: Материнская плата 28*24 (см) (DZ-982PVHL-GD0ALNOVW-V2.0)	1	[{"added": {}}]	7	1
4	2026-04-09 05:34:02.824514+00	3	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.1)	1	[{"added": {}}]	7	1
5	2026-04-09 05:36:09.017154+00	4	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.13)	1	[{"added": {}}]	7	1
6	2026-04-09 05:56:00.914964+00	5	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVHL-G00S-V1.1)	1	[{"added": {}}]	7	1
7	2026-04-09 05:57:19.045404+00	5	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVHL-G00S-V1.1)	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
8	2026-04-09 06:01:29.058318+00	6	Плата Android: Материнская плата (DZ-B-982P-V1.3)	1	[{"added": {}}]	7	1
9	2026-04-09 06:08:35.106429+00	6	Плата Android: Материнская плата 20*22,5 (см) (DZ-B-982P-V1.3)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
10	2026-04-09 06:13:31.314922+00	7	Плата Android: Материнская плата 28*24 (см) (DZ-982PVEJ-GD0ALVW-V2.0)	1	[{"added": {}}]	7	1
11	2026-04-09 06:54:30.53501+00	8	Плата Android: Плата питания 32*23 (см) (MP360SL-L4-S20)	1	[{"added": {}}]	7	1
12	2026-04-09 07:56:00.721842+00	9	Плата Android: Плата питания 32*23 (см) (MP380SL-5R62)	1	[{"added": {}}]	7	1
13	2026-04-09 10:50:58.186324+00	8	Плата Android: Плата питания 32*23 (см) (MP360SL-L4-S20)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
14	2026-04-09 10:55:32.07084+00	3	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.1)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
15	2026-04-09 10:56:29.849265+00	3	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.1)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
16	2026-04-10 04:25:32.379747+00	8	Плата Android: Плата питания 32*23 (см) (MP360SL-L4-S20)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
17	2026-04-10 04:31:46.924886+00	9	Плата Android: Плата питания 32*23 (см) (MP380SL-5R62)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
18	2026-04-10 04:33:32.460778+00	3	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.1)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
19	2026-04-10 04:34:45.617164+00	6	Плата Android: Материнская плата 20*22,5 (см) (DZ-B-982P-V1.3)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
20	2026-04-10 04:35:55.147152+00	2	Плата Android: Материнская плата 28*24 (см) (DZ-982PVHL-GD0ALNOVW-V2.0)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
21	2026-04-10 04:38:07.362307+00	1	Плата Android: Материнская плата 28*24 (см) (DZ-982PVEJ-GD0ALNOVW-V2.13)	2	[{"changed": {"fields": ["\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c", "\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
22	2026-04-10 04:39:30.098607+00	7	Плата Android: Материнская плата 28*24 (см) (DZ-982PVEJ-GD0ALVW-V2.0)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
23	2026-04-10 04:40:01.583888+00	5	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVHL-G00S-V1.1)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
24	2026-04-10 04:45:13.068332+00	4	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.13)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
25	2026-04-14 05:58:59.94597+00	10	Плата Android: Плата питания 29*21 (см) (MP380SL-5R34)	1	[{"added": {}}]	7	1
26	2026-04-14 06:02:40.630882+00	11	Плата Android: Плата питания 29*20 (см) (MP330SL+5R)	1	[{"added": {}}]	7	1
27	2026-04-14 06:05:24.113224+00	11	Плата Android: Плата питания 29*20 (см) (MP330SL-5R34X-D16)	2	[{"changed": {"fields": ["\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c", "\\u041c\\u043e\\u0434\\u0438\\u0444\\u0438\\u043a\\u0430\\u0446\\u0438\\u044f", "\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e", "\\u041c\\u0435\\u0441\\u0442\\u043e \\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u0438\\u044f", "\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
28	2026-04-14 06:06:41.561264+00	11	Плата Android: Плата питания 29*20 (см) (MP330SL-5R34X-D16)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
29	2026-04-14 06:17:58.632463+00	12	Плата Android: Плата питания 32*23 (см) (MP550SM-5S34-AD)	1	[{"added": {}}]	7	1
30	2026-04-14 06:56:07.402388+00	13	Платы Windows: Материнская плата для панели (QM6616)	1	[{"added": {}}]	7	1
31	2026-04-14 07:07:48.910869+00	13	Платы Windows: Материнская плата для панели (QM6616- I5-3320M)	2	[{"changed": {"fields": ["\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c", "\\u041c\\u043e\\u0434\\u0438\\u0444\\u0438\\u043a\\u0430\\u0446\\u0438\\u044f"]}}]	7	1
32	2026-04-14 07:17:25.313943+00	14	Платы Windows: Патеринская плата (QM6616 - I3-3120M)	1	[{"added": {}}]	7	1
33	2026-04-14 07:26:34.690266+00	14	Платы Windows: Материнская плата для панели (QM6616 - I3-3120M)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
34	2026-04-14 07:45:59.989433+00	15	Платы Windows: Материнская плата для панели (QM8000 - i3 - 4170)	1	[{"added": {}}]	7	1
35	2026-04-14 07:50:52.841117+00	16	Платы Windows: Материнская плата для панели (ELSKY QM8000 - 2C)	1	[{"added": {}}]	7	1
36	2026-04-15 04:17:33.527443+00	17	Платы Windows: Материнская плата для панели (BNY-I3-3120M-X86)	1	[{"added": {}}]	7	1
37	2026-04-16 02:51:37.384709+00	18	Платы Windows: Материнская плата для OPS (I5-11400)	1	[{"added": {}}]	7	1
38	2026-04-16 04:16:43.228876+00	19	Платы Windows: Материнская плата для OPS (I3-4160)	1	[{"added": {}}]	7	1
39	2026-04-16 05:02:05.759609+00	20	Плата Android: Плата питания 28*19 (см) (TOSN-LD6518P)	1	[{"added": {}}]	7	1
40	2026-04-16 05:09:25.609462+00	21	Плата Android: Плата питания 28*19 (см) (TOSN-LD5518P)	1	[{"added": {}}]	7	1
41	2026-04-16 05:14:11.639347+00	22	Плата Android: Плата питания 28*19 (см) (ZW9300-A-01-P02)	1	[{"added": {}}]	7	1
42	2026-04-16 05:22:53.46335+00	21	Плата Android: Плата питания 28*19 (см) (TOSN-LD5518P)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
43	2026-04-16 05:24:05.966994+00	20	Плата Android: Плата питания 28*19 (см) (TOSN-LD6518P)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
44	2026-04-16 05:30:20.241447+00	3	Плата Android: Материнская плата 20*22,5 (см) (DZ-982PVEJ-G00S-V1.1)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
45	2026-04-16 07:53:35.987346+00	23	Платы Windows: Плата питания 18*11 (см) (JP3250PL)	1	[{"added": {}}]	7	1
46	2026-04-16 07:57:53.218907+00	24	Платы Windows: Плата питания 18*11 (см) (JP3250AL)	1	[{"added": {}}]	7	1
47	2026-04-17 05:37:17.728805+00	25	Платы Windows: Плата питания для панели (JP4265AL)	1	[{"added": {}}]	7	1
48	2026-04-17 05:38:36.903558+00	19	Платы Windows: Материнская плата для OPS (I3-4160)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440"]}}]	7	1
49	2026-04-17 05:38:51.489779+00	18	Платы Windows: Материнская плата для OPS (I5-11400)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440"]}}]	7	1
50	2026-04-17 05:39:12.292535+00	17	Платы Windows: Материнская плата для панели (BNY-I3-3120M-X86)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
51	2026-04-17 05:39:44.021451+00	16	Платы Windows: Материнская плата для панели (ELSKY QM8000 - 2C)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
52	2026-04-17 05:40:02.411766+00	15	Платы Windows: Материнская плата для панели (QM8000 - i3 - 4170)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
53	2026-04-17 05:40:21.244731+00	14	Платы Windows: Материнская плата для панели (QM6616 - I3-3120M)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
54	2026-04-17 05:40:49.29924+00	13	Платы Windows: Материнская плата для панели (QM6616- I5-3320M)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440"]}}]	7	1
55	2026-04-17 06:17:19.839943+00	26	Платы Windows: Плата драйвера ЖК-экрана (M56W-V2.0)	1	[{"added": {}}]	7	1
56	2026-04-17 06:29:30.231271+00	27	Платы Windows: Плата питания (ZW8160)	1	[{"added": {}}]	7	1
57	2026-04-17 06:33:41.995841+00	28	Платы Windows: Плата питания для видеостены (JP150L)	1	[{"added": {}}]	7	1
58	2026-04-17 06:38:12.070057+00	29	Платы Windows: Плата питания (TOSN-LD4209P)	1	[{"added": {}}]	7	1
59	2026-04-17 06:38:31.407932+00	28	Платы Windows: Плата питания (JP150L)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
60	2026-04-17 06:39:37.077625+00	29	Платы Windows: Плата питания (TOSN-LD4209P)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
61	2026-04-17 06:45:25.685653+00	30	Платы Windows: Плата питания (PW.186W1.801)	1	[{"added": {}}]	7	1
62	2026-04-17 06:52:39.400877+00	30	Платы Windows: Плата питания Видеостены (PW.186W1.801)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
63	2026-04-17 06:52:52.333063+00	29	Платы Windows: Плата питания Видеостены (TOSN-LD4209P)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
64	2026-04-17 06:53:09.03426+00	28	Платы Windows: Плата питания Видеостены (JP150L)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
65	2026-04-17 06:53:21.91203+00	27	Платы Windows: Плата питания Видеостены (ZW8160)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
66	2026-04-17 06:58:12.097708+00	31	T-Con плата: Плата драйвера ЖК-экрана (M59W V2.3)	1	[{"added": {}}]	7	1
67	2026-04-17 07:02:18.525313+00	31	T-Con плата: Плата драйвера ЖК-экрана (M59W V2.3)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
68	2026-04-17 07:02:26.966862+00	30	T-Con плата: Плата питания Видеостены (PW.186W1.801)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
69	2026-04-17 07:02:38.067695+00	29	T-Con плата: Плата питания Видеостены (TOSN-LD4209P)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
70	2026-04-17 07:03:02.168612+00	28	T-Con плата: Плата питания Видеостены (JP150L)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
71	2026-04-17 07:03:12.475307+00	27	T-Con плата: Плата питания Видеостены (ZW8160)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
72	2026-04-17 07:03:33.912217+00	26	T-Con плата: Плата драйвера ЖК-экрана (M56W-V2.0)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
73	2026-04-17 07:09:35.350519+00	32	Плата Android: Плата питания 18*8,5 (см) (TOSN-LD1215P)	1	[{"added": {}}]	7	1
74	2026-04-17 07:12:19.294516+00	32	Плата Android: Плата питания 18*8,5 (см) (TOSN-LD1215P)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
75	2026-04-17 07:16:02.898189+00	33	T-Con плата: Плата питания Видеостены (MLT188T)	1	[{"added": {}}]	7	1
76	2026-04-19 10:41:51.99855+00	31	Видеостена: Плата драйвера ЖК-экрана (M59W V2.3)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
77	2026-04-19 10:42:00.986192+00	26	Видеостена: Плата драйвера ЖК-экрана (M56W-V2.0)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
78	2026-04-19 10:42:11.987511+00	31	Видеостена: Плата драйвера ЖК-экрана (M59W V2.3)	2	[]	7	1
79	2026-04-19 10:42:19.407906+00	33	Видеостена: Плата питания Видеостены (MLT188T)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
80	2026-04-19 10:42:27.83226+00	30	Видеостена: Плата питания Видеостены (PW.186W1.801)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
81	2026-04-19 10:42:36.758054+00	29	Видеостена: Плата питания Видеостены (TOSN-LD4209P)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
82	2026-04-19 10:42:45.465292+00	28	Видеостена: Плата питания Видеостены (JP150L)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
83	2026-04-19 10:42:54.175906+00	27	Видеостена: Плата питания Видеостены (ZW8160)	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u043e\\u0431\\u043e\\u0440\\u0443\\u0434\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"]}}]	7	1
84	2026-04-19 10:46:23.101331+00	25	Платы Windows: Плата питания для панели (JP4265AL)	2	[{"changed": {"fields": ["\\u041f\\u0440\\u043e\\u0446\\u0435\\u0441\\u0441\\u043e\\u0440"]}}]	7	1
85	2026-04-19 10:47:08.19731+00	25	Платы Windows: Плата питания для панели (JP4265AL)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
86	2026-04-21 07:18:50.647605+00	31	Видеостена: Плата драйвера ЖК-экрана (M59W V2.3)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
87	2026-04-21 07:28:46.104564+00	34	Шлейф: Шлейф (AWM 20624)	1	[{"added": {}}]	7	1
88	2026-04-21 07:32:08.194598+00	34	Шлейф: Шлейф (AWM 20624)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
89	2026-04-21 07:34:45.551213+00	34	Шлейф: Шлейф (AWM 20624)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
90	2026-04-21 07:42:44.112593+00	35	Шлейф: Шлейф 14 Pin (AWM 20624)	1	[{"added": {}}]	7	1
91	2026-04-21 07:42:58.101378+00	34	Шлейф: Шлейф 14 Pin (AWM 20624)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
92	2026-04-21 07:48:12.750109+00	35	Шлейф: Шлейф 14 Pin (AWM 20624)	2	[{"changed": {"fields": ["\\u0414\\u043b\\u0438\\u043d\\u0430 (\\u0441\\u043c)", "\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
93	2026-04-21 08:00:20.463998+00	35	Шлейф: Шлейф 14 Pin (AWM 20624)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
94	2026-04-21 08:01:31.189998+00	35	Шлейф: Шлейф 14 Pin (AWM 20624)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
95	2026-04-21 12:50:19.037473+00	35	Шлейф: Шлейф 14 Pin (AWM 20624)	2	[{"changed": {"fields": ["\\u041c\\u0435\\u0441\\u0442\\u043e \\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u0438\\u044f"]}}]	7	1
96	2026-04-22 01:46:57.60757+00	31	Видеостена: Плата драйвера ЖК-экрана (M59W V2.3)	2	[{"changed": {"fields": ["\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
97	2026-04-22 02:11:04.497527+00	36	Шлейф: Шлейф 14 Pin (AWM 20624)	1	[{"added": {}}]	7	1
98	2026-04-22 02:26:55.619954+00	36	Шлейф: Шлейф 14 Pin (AWM 20624)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e", "\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
99	2026-04-22 02:37:09.307647+00	37	Шлейф: Шлейф 14 Pin (AWM 20624)	1	[{"added": {}}]	7	1
100	2026-04-22 02:39:32.839908+00	37	Шлейф: Шлейф 14 Pin (7) (AWM 20624)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u0421\\u0441\\u044b\\u043b\\u043a\\u0430 \\u043d\\u0430 \\u0444\\u043e\\u0442\\u043e"]}}]	7	1
101	2026-04-22 02:39:48.726272+00	34	Шлейф: Шлейф 14 Pin (12) (AWM 20624)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
102	2026-04-22 02:40:09.058443+00	35	Шлейф: Шлейф 14 Pin (20) (AWM 20624)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
103	2026-04-22 02:40:52.129647+00	36	Шлейф: Шлейф 14 Pin (5) (AWM 20624)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
104	2026-04-22 07:36:17.103403+00	38	Шлейф: Шлейф 60 Pin (20) (AWM 20706)	1	[{"added": {}}]	7	1
105	2026-04-22 07:51:53.059012+00	39	Шлейф: Шлейф 60 Pin (20) (AWM 20706 (10))	1	[{"added": {}}]	7	1
106	2026-04-22 07:52:11.82397+00	39	Шлейф: Шлейф 60 Pin (10) (AWM 20706 (10))	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
107	2026-04-22 07:55:36.676485+00	40	Шлейф: Шлейф 60 Pin (15) (AWM 20706)	1	[{"added": {}}]	7	1
108	2026-04-22 08:02:55.13117+00	41	Шлейф: Шлейф 90 Pin (15) (AWM 20706)	1	[{"added": {}}]	7	1
109	2026-04-22 08:04:30.096656+00	39	Шлейф: Шлейф 60 Pin (10) (AWM 20706 (10))	2	[{"changed": {"fields": ["\\u041c\\u0435\\u0441\\u0442\\u043e \\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u0438\\u044f"]}}]	7	1
110	2026-04-23 02:29:51.201931+00	42	Шлейф: Шлейф 50 pin (AWM 20890)	1	[{"added": {}}]	7	1
111	2026-04-23 02:42:33.307787+00	43	Шлейф: Шлейф 50 pin (AWM 20890)	1	[{"added": {}}]	7	1
112	2026-04-23 02:42:52.770432+00	43	Шлейф: Шлейф 50 pin  (75) (AWM 20890)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
113	2026-04-23 02:43:08.688773+00	42	Шлейф: Шлейф 50 pin (90) (AWM 20890)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
114	2026-04-23 02:47:33.11683+00	44	Шлейф: Шлейф 50 pin (75) (AWM 20890)	1	[{"added": {}}]	7	1
115	2026-04-23 02:50:18.646894+00	39	Шлейф: Шлейф 60 Pin (10) (AWM 20706)	2	[{"changed": {"fields": ["\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c"]}}]	7	1
116	2026-04-23 02:54:21.91603+00	45	Шлейф: Шлейф 50 pin (AWM 20706)	1	[{"added": {}}]	7	1
117	2026-04-23 02:58:16.856249+00	45	Шлейф: Шлейф 50 pin (AWM 20706)	2	[{"changed": {"fields": ["\\u0414\\u043b\\u0438\\u043d\\u0430 (\\u0441\\u043c)"]}}]	7	1
118	2026-04-23 02:59:16.057475+00	46	Шлейф: Шлейф 50 pin (AWM 20706)	1	[{"added": {}}]	7	1
119	2026-04-23 03:03:25.171113+00	46	Шлейф: Шлейф 50 pin (AWM 20706)	2	[{"changed": {"fields": ["\\u041c\\u0435\\u0441\\u0442\\u043e \\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u0438\\u044f"]}}]	7	1
120	2026-04-23 03:03:33.916355+00	45	Шлейф: Шлейф 50 pin (AWM 20706)	2	[{"changed": {"fields": ["\\u041c\\u0435\\u0441\\u0442\\u043e \\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u0438\\u044f"]}}]	7	1
121	2026-04-23 05:21:51.152844+00	47	T-Con плата: Плата T-con SG7461D03-1 (SG7461D03-1)	1	[{"added": {}}]	7	1
122	2026-04-23 05:29:29.411401+00	48	T-Con плата: T-con ST4251B05-2-C-1 (ST4251B05-2-C-1)	1	[{"added": {}}]	7	1
123	2026-04-23 05:33:51.336095+00	49	T-Con плата: T-con ST4251B05-2-C-1 (ST4251B05-2-C-1)	1	[{"added": {}}]	7	1
124	2026-04-23 05:37:00.056476+00	48	T-Con плата: T-con TC.B550UHDQUB-F70.1 (TC.B550UHDQUB-F70.1)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c"]}}]	7	1
125	2026-04-23 05:38:30.650984+00	49	T-Con плата: T-con TC.B550UHDQUB-F70.1 (TC.B550UHDQUB-F70.1)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c"]}}]	7	1
126	2026-04-23 05:38:32.860846+00	48	T-Con плата: T-con ST4251B05-2-C-1 (ST4251B05-2-C-1)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c"]}}]	7	1
127	2026-04-24 01:23:10.544338+00	50	T-Con плата: T-con 65T55-C04 CTRL BD (65T55-C04 CTRL BD)	1	[{"added": {}}]	7	1
128	2026-04-24 01:28:11.489236+00	51	T-Con плата: T-con ST5461D18-2 (ST5461D18-2)	1	[{"added": {}}]	7	1
129	2026-04-24 01:42:32.855512+00	52	T-Con плата: T-con 55NB / 55OTW (55NB / 55OTW)	1	[{"added": {}}]	7	1
130	2026-04-24 01:47:18.62183+00	53	T-Con плата: T-con 65 6871L (65 6871L)	1	[{"added": {}}]	7	1
131	2026-04-24 01:53:01.9074+00	54	T-Con плата: T-Con HV320FHB-N02 (HV320FHB-N02)	1	[{"added": {}}]	7	1
132	2026-04-24 01:59:38.895289+00	55	T-Con плата: T-Con ST5461D07-1-C-D (ST5461D07-1-C-D)	1	[{"added": {}}]	7	1
133	2026-04-24 02:04:14.212675+00	56	T-Con плата: T-con 32T42-C0K (32T42-C0K)	1	[{"added": {}}]	7	1
134	2026-04-24 02:20:48.535934+00	54	T-Con плата: T-Con HV320FHB-N02 (HV320FHB-N02)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e"]}}]	7	1
135	2026-04-24 02:26:34.942827+00	57	T-Con плата: T-con 85T14 C03 CTRL (85T14 C03 CTRL)	1	[{"added": {}}]	7	1
136	2026-04-24 02:29:23.730106+00	51	T-Con плата: T-con LQ-K8-K03-12 (LQ-K8-K03-12)	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0438\\u043c\\u0435\\u043d\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u041c\\u043e\\u0434\\u0435\\u043b\\u044c"]}}]	7	1
137	2026-04-24 02:32:14.215227+00	58	T-Con плата: T-con DCBDP-C260A_20 (DCBDP-C260A_20)	1	[{"added": {}}]	7	1
138	2026-04-24 02:46:44.423912+00	59	T-Con плата: T-con 55A- UNB - PLUS-CPCB H/F (55A- UNB - PLUS-CPCB H/F)	1	[{"added": {}}]	7	1
139	2026-04-24 02:49:03.861229+00	60	T-Con плата: T-con DCBU-C196A_13_P3 (DCBU-C196A_13_P3)	1	[{"added": {}}]	7	1
140	2026-04-24 02:52:46.822912+00	55	T-Con плата: T-Con ST5461D07-1-C-D (ST5461D07-1-C-D)	2	[{"changed": {"fields": ["\\u041a\\u043e\\u043b\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e", "\\u041e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435"]}}]	7	1
141	2026-04-24 02:55:37.616203+00	61	T-Con плата: T-con ST4251B05-2-C-1 (ST4251B05-2-C-1)	1	[{"added": {}}]	7	1
142	2026-04-24 03:08:03.830269+00	62	T-Con плата: T-con HV490FHB-N80 (HV490FHB-N80)	1	[{"added": {}}]	7	1
143	2026-04-24 04:05:01.454151+00	63	T-Con плата: T-con ST7461D01-8 (ST7461D01-8)	1	[{"added": {}}]	7	1
144	2026-04-24 04:08:09.218438+00	64	T-Con плата: T-con ST6451D02-E (ST6451D02-E)	1	[{"added": {}}]	7	1
145	2026-04-24 04:35:26.088394+00	65	T-Con плата: Тач контроллер для 75" BlackBoard (Не известно)	1	[{"added": {}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounting	equipment
8	accounting	repairrequest
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-07 01:39:30.009139+00
2	auth	0001_initial	2026-04-07 01:39:30.219355+00
3	accounting	0001_initial	2026-04-07 01:39:30.318881+00
4	admin	0001_initial	2026-04-07 01:39:30.341227+00
5	admin	0002_logentry_remove_auto_add	2026-04-07 01:39:30.348318+00
6	admin	0003_logentry_add_action_flag_choices	2026-04-07 01:39:30.416295+00
7	contenttypes	0002_remove_content_type_name	2026-04-07 01:39:30.433968+00
8	auth	0002_alter_permission_name_max_length	2026-04-07 01:39:30.445313+00
9	auth	0003_alter_user_email_max_length	2026-04-07 01:39:30.455999+00
10	auth	0004_alter_user_username_opts	2026-04-07 01:39:30.464952+00
11	auth	0005_alter_user_last_login_null	2026-04-07 01:39:30.476346+00
12	auth	0006_require_contenttypes_0002	2026-04-07 01:39:30.479331+00
13	auth	0007_alter_validators_add_error_messages	2026-04-07 01:39:30.490152+00
14	auth	0008_alter_user_username_max_length	2026-04-07 01:39:30.501415+00
15	auth	0009_alter_user_last_name_max_length	2026-04-07 01:39:30.510736+00
16	auth	0010_alter_group_name_max_length	2026-04-07 01:39:30.521148+00
17	auth	0011_update_proxy_permissions	2026-04-07 01:39:30.528972+00
18	auth	0012_alter_user_first_name_max_length	2026-04-07 01:39:30.538868+00
19	sessions	0001_initial	2026-04-07 01:39:30.549839+00
20	accounting	0002_alter_equipment_image	2026-04-09 10:49:08.731493+00
21	accounting	0003_equipment_cpu	2026-04-16 13:03:24.222051+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: warehouse_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
tbvcd5xlkh0bjzaauj9rv41vpl29mmwy	.eJxVjEEOwiAQAP_C2ZCyXUA8evcNBJZFqgaS0p6MfzckPeh1ZjJv4cO-Fb93Xv2SxEUocfplMdCT6xDpEeq9SWp1W5coRyIP2-WtJX5dj_ZvUEIvY2ucAiTDhDRlBKNJQyK26qyR7TzHKasINqlMCvIMCGTIOsOcrUYnPl_O_jd1:1w9wKE:WcTNp4L0l8y3iYx1K9b7VZNEWZZ9wz5OjIXHJX1c0Ds	2026-04-21 02:37:58.86199+00
j4s25d58akqckqu2pe3j4fqxzb30zgup	.eJxVjEEOwiAQAP_C2ZCyXUA8evcNBJZFqgaS0p6MfzckPeh1ZjJv4cO-Fb93Xv2SxEUocfplMdCT6xDpEeq9SWp1W5coRyIP2-WtJX5dj_ZvUEIvY2ucAiTDhDRlBKNJQyK26qyR7TzHKasINqlMCvIMCGTIOsOcrUYnPl_O_jd1:1wA4tP:YsFgHnWZhmmQmy7bt31jLF-HLx0I2N8IHT78vzJd3k8	2026-04-21 11:46:51.984196+00
nvuqj8etw9ka3ecb20e1uto93nwsrkni	.eJxVjEEOwiAQAP_C2ZCyXUA8evcNBJZFqgaS0p6MfzckPeh1ZjJv4cO-Fb93Xv2SxEUocfplMdCT6xDpEeq9SWp1W5coRyIP2-WtJX5dj_ZvUEIvY2ucAiTDhDRlBKNJQyK26qyR7TzHKasINqlMCvIMCGTIOsOcrUYnPl_O_jd1:1wF5Kd:VvIqCH7gzpBoboOFrlQ1-8so6-TIY43cuqO2uM4dpTc	2026-05-05 07:15:39.507457+00
5qlj5ggc0pwc8g8qr9i38kr281ho5n6l	.eJxVjEEOwiAQAP_C2ZCyXUA8evcNBJZFqgaS0p6MfzckPeh1ZjJv4cO-Fb93Xv2SxEUocfplMdCT6xDpEeq9SWp1W5coRyIP2-WtJX5dj_ZvUEIvY2ucAiTDhDRlBKNJQyK26qyR7TzHKasINqlMCvIMCGTIOsOcrUYnPl_O_jd1:1wFAWb:AoTSyu1NnxXWceWGNtZ23vltaZl8qJAqQBBPUe2MICg	2026-05-05 12:48:21.063536+00
\.


--
-- Name: accounting_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.accounting_equipment_id_seq', 65, true);


--
-- Name: accounting_repairrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.accounting_repairrequest_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 32, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 145, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 8, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: warehouse_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- Name: accounting_equipment accounting_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.accounting_equipment
    ADD CONSTRAINT accounting_equipment_pkey PRIMARY KEY (id);


--
-- Name: accounting_repairrequest accounting_repairrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.accounting_repairrequest
    ADD CONSTRAINT accounting_repairrequest_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: accounting_repairrequest_approved_user_id_96b7db84; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX accounting_repairrequest_approved_user_id_96b7db84 ON public.accounting_repairrequest USING btree (approved_user_id);


--
-- Name: accounting_repairrequest_equipment_id_447aeb58; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX accounting_repairrequest_equipment_id_447aeb58 ON public.accounting_repairrequest USING btree (equipment_id);


--
-- Name: accounting_repairrequest_requesting_user_id_a8f3b116; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX accounting_repairrequest_requesting_user_id_a8f3b116 ON public.accounting_repairrequest USING btree (requesting_user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: warehouse_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounting_repairrequest accounting_repairreq_approved_user_id_96b7db84_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.accounting_repairrequest
    ADD CONSTRAINT accounting_repairreq_approved_user_id_96b7db84_fk_auth_user FOREIGN KEY (approved_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounting_repairrequest accounting_repairreq_equipment_id_447aeb58_fk_accountin; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.accounting_repairrequest
    ADD CONSTRAINT accounting_repairreq_equipment_id_447aeb58_fk_accountin FOREIGN KEY (equipment_id) REFERENCES public.accounting_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounting_repairrequest accounting_repairreq_requesting_user_id_a8f3b116_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.accounting_repairrequest
    ADD CONSTRAINT accounting_repairreq_requesting_user_id_a8f3b116_fk_auth_user FOREIGN KEY (requesting_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: warehouse_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--



--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--



--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--



--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--



--
-- PostgreSQL database dump complete
--

