# Generated by Django 6.0.3 on 2026-03-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('equip_type', models.CharField(choices=[('android_board', 'Плата Android'), ('windows_board', 'Платы Windows'), ('tcon', 'T-Con плата'), ('cable', 'Шлейф')], max_length=20, verbose_name='Тип оборудования')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('modification', models.CharField(blank=True, max_length=100, verbose_name='Модификация')),
                ('length_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина (см)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('cells', models.CharField(blank=True, max_length=100, verbose_name='Место хранения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/equipment/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Единица оборудования',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Запрошено кол-во')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.equipment', verbose_name='Запчасть для ремонта')),
                ('requesting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
        ),
    ]
