# Generated by Django 6.0.3 on 2026-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('equip_type', models.CharField(choices=[('android_board', 'Плата Android'), ('windows_board', 'Платы Windows'), ('tcon', 'T-Con плата'), ('cable', 'Шлейф')], max_length=20, verbose_name='Тип оборудования')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('modification', models.CharField(blank=True, max_length=100, verbose_name='Модификация')),
                ('length_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина (см)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('cells', models.CharField(blank=True, max_length=100, verbose_name='Место хранения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/equipment/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Единица оборудования',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
    ]
