# Generated by Django 6.0.3 on 2026-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cpu',
            field=models.CharField(blank=True, max_length=10, verbose_name='Процессор'),
        ),
    ]
