# Generated by Django 6.0.3 on 2026-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_equipment_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equip_type',
            field=models.CharField(choices=[('android_board', 'Плата Android'), ('windows_board', 'Платы Windows'), ('tcon', 'T-Con плата'), ('cable', 'Шлейф'), ('videowall', 'Видеостена')], max_length=20, verbose_name='Тип оборудования'),
        ),
    ]
